In [1]:
!mamba install pandas

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 0.9463000001907349 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        3.0.1                         np22py313h9d9dc1e_0           emscripten-forge
+ python-tzdata                 2025.3                        pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.1'

In [4]:
data = {
    "Name":["Roshan","Ram","Rinku"],
    "Age":[23,21,22],
    "Salary":[49000,34000,54000]
}

In [5]:
df = pd.DataFrame(data)

In [8]:
print(df)

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [11]:
df.describe()

        Age        Salary
count   3.0      3.000000
mean   22.0  45666.666667
std     1.0  10408.329997
min    21.0  34000.000000
25%    21.5  41500.000000
50%    22.0  49000.000000
75%    22.5  51500.000000
max    23.0  54000.000000

In [12]:
df.shape

(3, 3)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 132.0 bytes

In [14]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [15]:
df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [20]:
df_renamed_col = df.rename(columns={"Salary": "Monthly_Salary"})

In [21]:
df_renamed_col

     Name  Age  Monthly_Salary
0  Roshan   23           49000
1     Ram   21           34000
2   Rinku   22           54000

In [22]:
df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [25]:
df.to_csv("Test_data.csv")

In [29]:
df.to_csv("Test_data.csv", index=False)

In [30]:
load_df = pd.read_csv("Test_data.csv")

In [31]:
load_df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [32]:
df.head()

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [33]:
df.head()

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [34]:
df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [35]:
df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [36]:
df.head(2)

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000

In [37]:
df[["Name"]]

     Name
0  Roshan
1     Ram
2   Rinku

In [38]:
df[["Name","Salary"]]

     Name  Salary
0  Roshan   49000
1     Ram   34000
2   Rinku   54000

In [39]:
df.loc[df.Name=="Roshan"]

     Name  Age  Salary
0  Roshan   23   49000

In [40]:
df.loc[0]

Name      Roshan
Age           23
Salary     49000
Name: 0, dtype: object

In [42]:
df.loc[0:2]

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [44]:
df.iloc[0:2]

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000

In [45]:
df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [53]:
df_age_filer = df[df["Age"]>21]
df_age_filer

     Name  Age  Salary
0  Roshan   23   49000
2   Rinku   22   54000

In [47]:
df_age_filer

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [54]:
df_age_filer = df[(df["Age"]>21) & (df["Salary"]>50000)]

In [55]:
df_age_filer

    Name  Age  Salary
2  Rinku   22   54000

In [56]:
df.where(df["Age"] >= 18)

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [57]:
df.where(df["Age"]>22)

     Name   Age   Salary
0  Roshan  23.0  49000.0
1     NaN   NaN      NaN
2     NaN   NaN      NaN

In [58]:
df.where(df["Age"] >= 22, other = "Not eligible")

           Name           Age        Salary
0        Roshan            23         49000
1  Not eligible  Not eligible  Not eligible
2         Rinku            22         54000

In [59]:
df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [63]:
df

     Name  Age  Salary
0  Roshan   23   49000
1     Ram   21   34000
2   Rinku   22   54000

In [66]:
df['Team'] = ['CEO', 'HR', 'CTO'] # creating a new column

In [67]:
df

     Name  Age  Salary Team
0  Roshan   23   49000  CEO
1     Ram   21   34000   HR
2   Rinku   22   54000  CTO

In [68]:
#Adding a new column using an existing column
df["Bonus"] = df["Salary"]*0.20 # here we are giving the 20% bonus to all the employee of thier actuall salary
df

     Name  Age  Salary Team    Bonus
0  Roshan   23   49000  CEO   9800.0
1     Ram   21   34000   HR   6800.0
2   Rinku   22   54000  CTO  10800.0

In [70]:
# gives the length of the dataframe like how many rows are there
len(df)

3

In [72]:
#Add a new row at the end of the dataframe
df.loc[len(df)] = ["Amit",19,34000,"Intern",1500]
df

     Name  Age  Salary    Team    Bonus
0  Roshan   23   49000     CEO   9800.0
1     Ram   21   34000      HR   6800.0
2   Rinku   22   54000     CTO  10800.0
3    Amit   19   34000  Intern   1500.0

In [73]:
df

     Name  Age  Salary    Team    Bonus
0  Roshan   23   49000     CEO   9800.0
1     Ram   21   34000      HR   6800.0
2   Rinku   22   54000     CTO  10800.0
3    Amit   19   34000  Intern   1500.0

In [74]:
#update the value in dataframe in row using index-name
df.loc[0,"Name"]= "Raghav"

In [75]:
df

     Name  Age  Salary    Team    Bonus
0  Raghav   23   49000     CEO   9800.0
1     Ram   21   34000      HR   6800.0
2   Rinku   22   54000     CTO  10800.0
3    Amit   19   34000  Intern   1500.0

In [77]:

# update the value in the dataframe using column value

df.loc[df.Name == "Raghav", "Name"] = "Roshan"
df

     Name  Age  Salary    Team    Bonus
0  Roshan   23   49000     CEO   9800.0
1     Ram   21   34000      HR   6800.0
2   Rinku   22   54000     CTO  10800.0
3    Amit   19   34000  Intern   1500.0

In [78]:
len(df)

4

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
 3   Team    4 non-null      str
 4   Bonus   4 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 200.0 bytes

In [80]:
df.shape

(4, 5)

In [81]:
#delete values rows and columns

In [82]:
# delete row using column-value filter 
df = df.drop(df[df.Name == "Ram"].index)
df

     Name  Age  Salary    Team    Bonus
0  Roshan   23   49000     CEO   9800.0
2   Rinku   22   54000     CTO  10800.0
3    Amit   19   34000  Intern   1500.0

In [84]:
# delete rown  using index-name filter
df.drop(2,axis = 0) # here 2 , axis = 0 means index number 2 and column i.e drop the row(from axis 0) whose index is 2

     Name  Age  Salary    Team   Bonus
0  Roshan   23   49000     CEO  9800.0
3    Amit   19   34000  Intern  1500.0

In [87]:
df.drop("Age",axis = 1)  # In pandas there is only two axis is there like 0 for y axis i.e vertical and axis 1 for the x axis i.e horizontal axis

     Name  Salary    Team    Bonus
0  Roshan   49000     CEO   9800.0
2   Rinku   54000     CTO  10800.0
3    Amit   34000  Intern   1500.0

In [ ]:
df.drop("Age",axis = 1) #drop the column(from axis=1) whose index label is "Age"

In [88]:
df

     Name  Age  Salary    Team    Bonus
0  Roshan   23   49000     CEO   9800.0
2   Rinku   22   54000     CTO  10800.0
3    Amit   19   34000  Intern   1500.0

In [89]:
df["Age"]=[21,24,21]
df

     Name  Age  Salary    Team    Bonus
0  Roshan   21   49000     CEO   9800.0
2   Rinku   24   54000     CTO  10800.0
3    Amit   21   34000  Intern   1500.0